name: tchapreader
version: "1.0.0"

services:
  - name: tchapreader
    port: 8087

pipelines:
  files: []

tools:
  entries:
    - id: tchapreader
      source_file: app/openwebui_tchap_tool.py
      service_name: tchapreader
      service_port: 8087
    - id: tchapreader_admin
      source_file: app/openwebui_tchap_admin_tool.py
      service_name: tchapreader
      service_port: 8087

model_tools: []

env_vars: []

k8s:
  namespace: owui-socle
  custom_image: true
