apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tchap-reader-data
  namespace: grafrag
  labels:
    app: tchap-reader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
