apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tchapreader-data
  namespace: grafrag
  labels:
    app: tchapreader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
