apiVersion: v1
kind: Service
metadata:
  name: tchapreader
  namespace: grafrag
  labels:
    app: tchapreader
spec:
  type: ClusterIP
  selector:
    app: tchapreader
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: http
